### ISSUE TITLE
Update BlueStyle docs?

### ISSUE THREAD

**Issue by nickrobinson251** [kdheepak/JuliaFormatter.vim#15]
Hello! 

Following JuliaFormatter.jl v0.9.0 there's a `BlueStyle` and since v0.9.1 it's enough to set `format = "blue"` in a `.JuliaFormatter.toml` or to run `format(path, BlueStyle())` (equivalently `format(path; style=BlueStyle())`
docs: https://domluna.github.io/JuliaFormatter.jl/dev/blue_style/

Since you're kind enough to have a [Readme section on compatibility with BlueStyle](https://github.com/kdheepak/JuliaFormatter.vim#compatibility-with-bluestyle), i wondered if it can/needs to be updated given the additions to JuliaFormatter in v0.9?

**Comment by nickrobinson251** [comment]
i tried `let g:JuliaFormatter_options = {'style': 'blue'}` but it gave `[JuliaFormatter] ERROR: JuliaFormatter.jl could not parse text.`, so i'm not sure quite what the right change is 😊

**Comment by nickrobinson251** [comment]
perhaps it requires some editing of the server code? e.g.
```diff
diff --git a/scripts/server.jl b/scripts/server.jl
index 8ea86f9..9a2b88f 100644
--- a/scripts/server.jl
+++ b/scripts/server.jl
@@ -28,6 +28,15 @@ function main()
         elseif data["method"] == "format"
             text = data["params"]["text"]
             options = data["params"]["options"]
+            style = get(options, "style", nothing)
+            options["style"] = style == "blue"
+                BlueStyle()
+            elseif
+                style == "yas"
+                YASStyle()
+            else
+                DefaultStyle()
+            end
             for (k,v) in options
                 format_options[Symbol(k)] = v
             end
```
But idk how to test changes locally -- not familiar with developing vim plugins :)

**Comment by kdheepak** [comment]
Great idea! If you update your vim plugin this will work :) 

I haven't been actively working in Julia recently, so I haven't been using the plugin. Feel free to open issues or feature requests if something doesn't work the way you expect!

**Comment by nickrobinson251** [comment]
awesome! thank you so much!
