### ISSUE TITLE
Support using configuration file

### ISSUE THREAD

**Issue by jw3126** [kdheepak/JuliaFormatter.vim#18]
I think it would be neat if JuliaFormatter.vim could search for a config file, like `JuliaFormatter.format` does:

https://domluna.github.io/JuliaFormatter.jl/stable/config/

Or is this maybe already possible?

**Comment by kdheepak** [comment]
Thanks for the suggestion! I didn't know that this feature was added to JuliaFormatter.jl. I've updated the plugin to support .JuliaFormatter.toml files.
