### ISSUE TITLE
Is there some way to not show the log message every time I open a file?

### ISSUE THREAD

**Issue by fchorney** [kdheepak/JuliaFormatter.vim#35]
### Troubleshooting

- vim 8.2
- 
```
(juliaformatter) pkg> st
      Status `/vim_location/juliaformatter/Project.toml`
  [682c06a0] JSON v0.21.1
  [98e50ef6] JuliaFormatter v0.15.0
  [9b87118b] PackageCompiler v1.2.6
```
-
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
  ```
  

Is there some way to skip the log message that shows up every time I open a file when I have `let g:JuliaFormatter_always_launch_server=1`? It's getting quite annoying to have to hit enter a second time every time I open a file.

Every file I open I get the following:
```
"ssh.jl" 36L, 1282B
[JuliaFormatter] started JuliaFormatter server (see :JuliaFormatterEchoCmd)julia --startup-file=no --color=no --project=/vim_location/juliaformatter /vim_location/juliaformatter/scripts/server.jl
Press ENTER or type command to continue
```

My vim settings for this plugin are as follows:

```
let g:JuliaFormatter_use_sysimg=1
let g:JuliaFormatter_always_launch_server=1

let g:JuliaFormatter_options = {
    \ 'style' : 'blue',
    \ }
```

**Comment by kdheepak** [comment]
Sorry! I had this change locally but didn't push it. Can you try the latest commit on the `master` branch?

**Comment by kdheepak** [comment]
Maybe if `let g:JuliaFormatter_always_launch_server=1` is set then this message is not useful. I think I can make that change too.

**Comment by fchorney** [comment]
Hmm it still makes me hit enter after it shows me this message.

**Comment by kdheepak** [comment]
I just pushed a couple of commits to the `master` branch. Can you update to the latest commit again and try it? In my testing locally it no longer prints anything for me.

**Comment by fchorney** [comment]
yes looks like it's not printing anymore. Thanks so much!
