### ISSUE TITLE
Add command (or instructions) on how to update

### ISSUE THREAD

**Issue by lassepe** [kdheepak/JuliaFormatter.vim#41]
With #40 the user now has to update the dependencies manually from time to time (it does not happen through `Pkg.instantiate` anymore). This should probably be documented. Or do we want a command like `JuliaFormatterUpdate` to run the updates from within vim?

**Comment by kdheepak** [comment]
Yeah I was going to add something like that after that PR.

**Comment by kdheepak** [comment]
There is a `:JuliaFormatterUpdate` now, added in this commit: https://github.com/kdheepak/JuliaFormatter.vim/commit/75446d9042ad6e475b8fab7caf93f61c293b374d
