### ISSUE TITLE
Dangerous behaviour when editing multiple files.

### ISSUE THREAD

**Issue by iago-lito** [kdheepak/JuliaFormatter.vim#45]
Hello, I would like to report a dangerous non-isolation of buffers when using JuliaFormatter. To reproduce, create the following two files on disk:
`julia_file.jl`
```
f=  function(some,poorly,
 formatted,  code) return 5; end
```

`unrelated_file.txt`
```
unrelated content
```

Then
1. Open code with `vim julia_file.jl`.
2. Consider the code is not nice, run `:JuliaFormatterFormat`.
3. It's taking a while the first time, take this opportunity to `:edit unrelated_file.txt`.
4. Wait a minute for the magic to happen.

JuliaFormatter formats the wrong buffer, and immediately saves the result on disk. At the end of the game:

`julia_file.jl` (unchanged)
```
f=  function(some,poorly,
 formatted,  code) return 5; end
```

`unrelated_file.txt` (corrupted)
```
f = function (some, poorly, formatted, code)
    return 5
end
```

The sad story is that I've just lost my entire `.vimrc` to this cr..corruption problem. It would've been.. preferable if this did not happen X(

Considering the formatting delay, can `JuliaFormatter` be careful not to naively edit the current buffer, but the one from which the formatting command was originally issued?

---

- `vim --version`
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `julia --project=/path/to/JuliaFormatter.vim/ -e "using Pkg; Pkg.status()"`
```
      Status `/opt/vim.plugged/JuliaFormatter.vim/Project.toml`
  [682c06a0] JSON v0.21.2
  [98e50ef6] JuliaFormatter v0.15.11
  [9b87118b] PackageCompiler v1.4.0
```
- `julia --project=/path/to/JuliaFormatter.vim/ -e "using InteractiveUtils; versioninfo()"`
```
Julia Version 1.7.0
Commit 3bf9d17731* (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, skylake)
```
`:JuliaFormatterLog`
```
[2021-12-17T10:11:35.544] calling main ...
[2021-12-17T10:11:40.448] Connected.
[2021-12-17T10:11:40.460] Setting up defaults ...
[2021-12-17T10:11:40.469] Searching for .JuliaFormatter.toml ...
[2021-12-17T10:11:40.469] No .JuliaFormatter.toml
[2021-12-17T10:11:40.535] Using options: Dict{Symbol, Any}(:indent => 4, :margin => 92, :always_for_in => false, :whitespace_typedefs => false, :whitespace_ops_in_indices => true, :style => DefaultStyle(nothing)) with style: DefaultStyle(nothing)
[2021-12-17T10:11:40.541] Formatting: 
[2021-12-17T10:11:40.553]

f=  function(some,poorly,
 formatted,  code) return 5; end

[2021-12-17T10:11:42.804] Success
[2021-12-17T10:11:42.804] 
---------------------------------------------------------------------

[2021-12-17T10:11:42.804] Formatted: 
[2021-12-17T10:11:42.804]

f = function (some, poorly, formatted, code)
    return 5
end

[2021-12-17T10:11:43.070] Done.
```

`:JuliaFormatterEchoCmd`
```
[JuliaFormatter] julia --startup-file=no --color=no --project=/opt/vim.plugged/JuliaFormatter.v
im /opt/vim.plugged/JuliaFormatter.vim/scripts/server.jl
```

**Comment by kdheepak** [comment]
Oh man, I'm sorry that happened. I'll fix this so that it checks that you are on the same buffer before editing the file.

**Comment by kdheepak** [comment]
Ideally, the "server" script would respond with the buffer number that is requesting the format, and the plugin would format that bufnr appropriately but I'm not able to get this to work in vim properly for some reason. 

The issue is I'm communicating with the server script using stdin and stdout, and when the response is JSON, I'm running into parsing issues for the json with vim. With neovim this works fine. 

I don't think this is an issue unless people want to be able to run JuliaFormatterFormat on multiple files at the same time and have the plugin do the right thing. So for now, this solution of storing it in a global variable will suffice.
